name: Try installing Node dependencies
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
            
      - name: ng build --prod
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
            ls
            echo "***********************************************"
            sudo apt update
            sudo apt install nodejs
            sudo apt install npm
            echo "******************* Node Version **************"
            nodejs -v
            sudo chown -R $USER /usr/local/lib/node_modules
            sudo npm install -g @angular/cli
            sudo npm install
            ng build --prod
           
      - name: Deploy to server
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "dist/my-app"
          dist_target_dir: "/public_html"
          delete: "true"
          exclude: "'^logs/' '^README.md'"
